/*
 * Code for class WEL_HT_CONSTANTS
 */

#include "eif_eiffel.h"
#include "../E1/estructure.h"


#ifdef __cplusplus
extern "C" {
#endif

extern EIF_TYPED_VALUE F1002_9077(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1002_9078(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1002_9079(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1002_9080(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1002_9081(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1002_9082(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1002_9083(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1002_9084(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1002_9085(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1002_9086(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1002_9087(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1002_9088(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1002_9089(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1002_9090(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1002_9091(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1002_9092(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1002_9093(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1002_9094(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1002_9095(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1002_9096(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1002_9097(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1002_9098(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1002_9099(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1002_9100(EIF_REFERENCE);
extern void EIF_Minit1002(void);

#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

/* {WEL_HT_CONSTANTS}.hterror */
EIF_TYPED_VALUE F1002_9077 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -2L);
	return r;
}

/* {WEL_HT_CONSTANTS}.httransparent */
EIF_TYPED_VALUE F1002_9078 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -1L);
	return r;
}

/* {WEL_HT_CONSTANTS}.htnowhere */
EIF_TYPED_VALUE F1002_9079 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_HT_CONSTANTS}.htclient */
EIF_TYPED_VALUE F1002_9080 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_HT_CONSTANTS}.htcaption */
EIF_TYPED_VALUE F1002_9081 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_HT_CONSTANTS}.htsysmenu */
EIF_TYPED_VALUE F1002_9082 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_HT_CONSTANTS}.htsize */
EIF_TYPED_VALUE F1002_9083 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_HT_CONSTANTS}.htmenu */
EIF_TYPED_VALUE F1002_9084 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5L);
	return r;
}

/* {WEL_HT_CONSTANTS}.hthscroll */
EIF_TYPED_VALUE F1002_9085 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6L);
	return r;
}

/* {WEL_HT_CONSTANTS}.htvscroll */
EIF_TYPED_VALUE F1002_9086 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 7L);
	return r;
}

/* {WEL_HT_CONSTANTS}.htminbutton */
EIF_TYPED_VALUE F1002_9087 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_HT_CONSTANTS}.htmaxbutton */
EIF_TYPED_VALUE F1002_9088 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 9L);
	return r;
}

/* {WEL_HT_CONSTANTS}.htleft */
EIF_TYPED_VALUE F1002_9089 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 10L);
	return r;
}

/* {WEL_HT_CONSTANTS}.htright */
EIF_TYPED_VALUE F1002_9090 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 11L);
	return r;
}

/* {WEL_HT_CONSTANTS}.httop */
EIF_TYPED_VALUE F1002_9091 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 12L);
	return r;
}

/* {WEL_HT_CONSTANTS}.httopleft */
EIF_TYPED_VALUE F1002_9092 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 13L);
	return r;
}

/* {WEL_HT_CONSTANTS}.httopright */
EIF_TYPED_VALUE F1002_9093 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 14L);
	return r;
}

/* {WEL_HT_CONSTANTS}.htbottom */
EIF_TYPED_VALUE F1002_9094 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 15L);
	return r;
}

/* {WEL_HT_CONSTANTS}.htbottomleft */
EIF_TYPED_VALUE F1002_9095 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_HT_CONSTANTS}.htbottomright */
EIF_TYPED_VALUE F1002_9096 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 17L);
	return r;
}

/* {WEL_HT_CONSTANTS}.htborder */
EIF_TYPED_VALUE F1002_9097 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 18L);
	return r;
}

/* {WEL_HT_CONSTANTS}.htgrowbox */
EIF_TYPED_VALUE F1002_9098 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_HT_CONSTANTS}.htreduce */
EIF_TYPED_VALUE F1002_9099 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_HT_CONSTANTS}.htzoom */
EIF_TYPED_VALUE F1002_9100 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 9L);
	return r;
}

void EIF_Minit1002 (void)
{
	GTCX
}


#ifdef __cplusplus
}
#endif
